### ISSUE TITLE
Header View Height Changed - Doesn't Space Allocated

### ISSUE THREAD

**Issue by daneren2005** [liaohuqiu/android-GridViewWithHeaderAndFooter#12]
When the header view's height is changed after the header has been added to the grid, it doesn't actually change the height of the header.  The case I am using is that there is some text with only some of it displayed in the header, and when the user clicks on it in enlarges to display everything.  I do this by increasing the max lines of the TextView.  When the header is attached to a ListView, this works fine.  When the header is attached to this GridViewWithHeaderAndFoot, the text grows but goes behind the main part of the grid since the header itself stays the exact same height.  Any idea where I should start looking to fix this?

**Comment by daneren2005** [comment]
I have also tried variations of stuff like this:

headerGridView.invalidateRowHeight();
headerGridView.requestLayout();
headerGridView.invalidate();

**Comment by liaohuqiu** [comment]
OK, I will try to fix this today.

**Comment by liaohuqiu** [comment]
I've post and demo to check this issue, it seems ok:  https://github.com/liaohuqiu/android-cube-app/blob/master/src/in/srain/cube/demo/ui/fragment/GridViewWithHeaderAndFooterFragment.java, 

https://github.com/liaohuqiu/android-cube-app/commit/d336fda244f1c7ac6e4ce53739fba4445528d97c

**Comment by daneren2005** [comment]
It might be because I am using a much more complicated layout in my header.  Here is the layout I am inflating and putting in the header: https://github.com/daneren2005/Subsonic/blob/master/res/layout/select_album_header.xml.  I am thinking it might be because the LinearLayout which contains the enlarging text is set to wrap_content and it is not recalculating.

**Comment by liaohuqiu** [comment]
Try to calll `notifyDataSetChanged()`, the GridView will re-layout.

**Comment by liaohuqiu** [comment]
I've updated the demo. The problem has been reproduced. If `notifyDataSetChanged()` did not be called, the header will not be re-layout. Simply call `notifyDataSetChanged()` will fix this. https://github.com/liaohuqiu/android-cube-app, https://github.com/liaohuqiu/android-cube-app/blob/4365b5388ba5fb8c36b8dca33b457b1060f9846f/src/in/srain/cube/demo/ui/fragment/GridViewWithHeaderAndFooterFragment.java

**Comment by daneren2005** [comment]
I have also tried setting the height of the header view itself which does not seem to make any difference:
```
FrameLayout.LayoutParams lyp = (FrameLayout.LayoutParams) header.getLayoutParams();
lyp.height = 1000;
header.setLayoutParams(lyp);
```

I am not sure what I am doing wrong here.  One difference between what I am doing is that you appear to be making the change as the data loads, where I am making the change at some arbitrary point later wen the user clicks the text.

**Comment by daneren2005** [comment]
That does indeed fix the problem, thank you!

**Comment by liaohuqiu** [comment]
:)

**Comment by daneren2005** [comment]
I would like to point out on a separate note, I was noticing a crash when fast scroller was enabled on some devices with this view.  Changing:
`private static class HeaderViewGridAdapter implements WrapperListAdapter, Filterable`
to
`private static class HeaderViewGridAdapter extends BaseAdapter implements WrapperListAdapter, Filterable`

seems to have gotten rid of the error.  I might not be full understanding the issue though, so it's possible that breaks something else.  But so far I haven't noticed any new issues from it.

**Comment by liaohuqiu** [comment]
I reopened this issue. That will be great if you notice the crash again and paste the backtrace information here. Thank your for you feedback. :+1:

**Comment by daneren2005** [comment]
java.lang.ClassCastException: github.daneren2005.dsub.view.HeaderGridView$HeaderViewGridAdapter cannot be cast to android.widget.BaseAdapter
at android.widget.FastScroller.getSectionsFromIndexer(FastScroller.java:875)
at android.widget.FastScroller.getPosFromItemCount(FastScroller.java:1147)
at android.widget.FastScroller.onItemCountChanged(FastScroller.java:453)
at android.widget.AbsListView.onLayout(AbsListView.java:2546)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15762)
at android.view.ViewGroup.layout(ViewGroup.java:4867)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
at android.view.Choreographer.doCallbacks(Choreographer.java:614)
at android.view.Choreographer.doFrame(Choreographer.java:584)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5487)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
