### ISSUE TITLE
Random NPE on Android 2.3.7 - Gingerbread API 10

### ISSUE THREAD

**Issue by wayneforrest** [liaohuqiu/android-GridViewWithHeaderAndFooter#43]
I have a GridView with widgets and inside a group widget the crash occurred 
it does not happen all the time. (The same grid gets used for groups and non group views).

Is this released to compile 'in.srain.cube:grid-view-with-header-footer:1.0.12'

Here is my stack trace..

FATAL EXCEPTION: main
java.lang.NullPointerException
    at android.widget.GridView.fillUp(GridView.java:311)
    at android.widget.GridView.fillGap(GridView.java:199)
    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:3422)
    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:2920)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3703)
    at java.lang.reflect.Method.invokeNative(Native Method)

01-20 14:26:05.968 10332-10332/za.co.nedsecure.nedbankSMAS.qa E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by wayneforrest** [comment]
The UI consists of a grid view with multiple widgets, and some of the widgets are of type group that contain more widgets, representing typical folders. At the very bottom of my grid view I have a image
that holds a logo.

When I open a group, the crash occurs but only occurs if I scroll far enough to make the logo visible.
If however do not make the logo visible the group can open without a crash.

I have looked here http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/2.3.7_r1/android/widget/GridView.java#GridView.0mReferenceView

and it seems that mReferenceView is null at line 311.  //mReferenceView will change with each call to makeRow()

**Comment by liaohuqiu** [comment]
I think it's a `fast scroll` issue.

**Comment by wayneforrest** [comment]
Found the issue caused by gridView.smoothScrollToPosition(0);

more details here: http://stackoverflow.com/questions/34904212/android-gingerbread-gridview-gives-nullpointerexception-android-widget-gridview/34988355#34988355

**Comment by liaohuqiu** [comment]
@wayneforrest  Great! Thanks a lot, :+1:
